// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbYePtK8osmpf6veXBHcXsLgLC8tXagb8',
    appId: '1:582007164570:web:4022714468aef862ecd923',
    messagingSenderId: '582007164570',
    projectId: 'control-cash-db548',
    authDomain: 'control-cash-db548.firebaseapp.com',
    storageBucket: 'control-cash-db548.firebasestorage.app',
    measurementId: 'G-7WJT89KTMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWaxxyQwivAi4XVmXrlzYK0WsI0F3NL78',
    appId: '1:582007164570:android:79c47afe6146c37becd923',
    messagingSenderId: '582007164570',
    projectId: 'control-cash-db548',
    storageBucket: 'control-cash-db548.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZQ1uV6rZFT2JUcK-_2JiimNXTEswWNjw',
    appId: '1:582007164570:ios:ef6cd78bb382f556ecd923',
    messagingSenderId: '582007164570',
    projectId: 'control-cash-db548',
    storageBucket: 'control-cash-db548.firebasestorage.app',
    iosBundleId: 'com.example.controlCash',
  );

}